---
swagger: "2.0"
info:
  description: "Multi line description for the MagicFAQ\
    \ API"
  version: "1.0.0"
  title: "MagicFAQ"
  contact:
    email: "jschilz@uw.edu"
  license:
    name: "MIT"
basePath: "/v1"

schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /questions:
    get:
      tags:
      - "questions"
      summary: "Finds questions."
      operationId: "findQuestions"
      parameters:
        - name: "question"
          in: "query"
          required: false
          type: "string"
        - name: "max"
          in: "query"
          description: "Maximum number of questions to return."
          required: false
          type: "integer"
        - name: "match-weight"
          in: "query"
          required: false
          type: "integer"
        - name: "recency[]"
          in: "query"
          description: "ISO 8601 formatted interval"
          required: false
          type: "array"
          items:
            type: "string"
          collectionFormat: "multi"
        - name: "recency-weight[]"
          in: "query"
          description: "Weight for corresponding interval"
          required: false
          type: "array"
          items:
            type: "integer"
          collectionFormat: "multi"
        - name: "context[]"
          in: "query"
          required: false
          type: "array"
          items:
            type: "string"
        - name: "context-weight"
          in: "query"
          required: false
          type: "integer"
        - name: "context-require"
          in: "query"
          required: false
          type: "string"
          enum:
            - "any"
            - "no"
        - name: "all"
          in: "query"
          required: false
          type: "boolean"
    post:
      tags:
      - "questions"
      summary: "Add a new question"
      description: ""
      operationId: "addQuestion"
      parameters:
        - in: formData
          name: "question"
          description: "Body of question to be added to the database"
          required: true
          type: "string"
        - in: formData
          name: "answer"
          description: "Body of accompanying answer"
          required: true
          type: "string"
      responses:
        405:
          description: "Invalid input"
  /questions/{question_id}/:
    patch:
      tags:
        - "questions"
      summary: "Update an existing question"
      description: ""
      operationId: "updateQuestion"
      parameters:
        - name: "question_id"
          in: "query"
          required: true
          type: "integer"
        - in: formData
          name: "question"
          description: "Body of question to be added to the database"
          required: false
          type: "string"
        - in: formData
          name: "answer"
          description: "Body of accompanying answer"
          required: false
          type: "string"
  /feedback/:
    post:
      tags:
        - "feedback"
      summary: "Provide feedback on a question"
      description: ""
      operationId: "provideFeedback"
      parameters:
        - name: "question_id"
          in: formData
          required: true
          type: "integer"
        - in: formData
          name: "question"
          required: true
          type: "string"
        - in: formData
          name: "magnitude"
          description: "Strength and valence of feedback"
          required: true
          type: "integer"
